[phases.setup]
nixPkgs = ["php81"]

[phases.install]
cmds = ["mkdir -p public"]

[phases.build]
cmds = [
    "cp -r sss/* public/",
    "echo '<?php echo json_encode([\"status\" => \"healthy\", \"timestamp\" => date(\"Y-m-d H:i:s\")]); ?>' > public/health.php"
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"
